# Generated by Django 3.0.4 on 2020-03-06 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('profesor', models.CharField(max_length=255)),
                ('temario', models.TextField()),
                ('imagen', models.FileField(blank=True, null=True, upload_to='cursos/imagenes')),
                ('creacion_curso', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
